export default {
  type: 'object',
  displayType: 'row',
  showDescIcon: true,
  labelWidth: 120,
  column: 3,
  properties: {
    begin: {
      title: 'begin',
      type: 'array',
      description: '布局的左上角对齐位置',
      default: [40, 40],
      widget: 'begin',
    },
    rankdir: {
      title: 'rankdir',
      type: 'string',
      description: '布局的方向，图的延展方向',
      default: 'LR',
      enum: ['TB', 'BT', 'LR', 'RL'],
      enumNames: ['由上到下', '由下到上', '由左到右', '由右到左'],
    },
    align: {
      title: 'align',
      type: 'string',
      description: '节点对齐方式',
      default: 'UL',
      enum: ['UL', 'UR', 'DL', 'DR', ''],
      enumNames: ['左上', '右上', '左下', '右下', '居中'],
      props: {
        allowClear: true,
      },
    },
    ranksep: {
      title: 'ranksep',
      type: 'number',
      description: '层间距（px）',
      default: 20,
    },
    nodesep: {
      title: 'nodesep',
      type: 'number',
      description: '节点间距（px）',
      default: 20,
    },
    ranker: {
      title: 'ranker',
      type: 'string',
      description: '节点分层3种布局方式',
      default: 'tight-tree',
      enum: ['tight-tree', 'longest-path', 'network-simplex'],
      enumNames: ['紧凑树', '最长路径', '网格单纯'],
    },
  },
};
